apiVersion: v1
kind: Service
metadata:
  name: cloud-app
  namespace: cloud-app
  labels:
    app: cloud-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 30080   # sau orice port între 30000-32767
  selector:
    app: cloud-app
