name: Build and Deploy to GKE

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'kubectl'

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials cloud-app-cluster --region europe-central2 --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Set Docker tag
        id: vars
        run: echo "TAG=v${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/cloud-app:${TAG}

      - name: Set image in deployment
        run: |
          kubectl set image deployment/cloud-app cloud-app=gcr.io/${{ secrets.GCP_PROJECT_ID }}/cloud-app:${TAG} -n cloud-app

      - name: Rollout status
        run: |
          kubectl rollout status deployment/cloud-app -n cloud-app
